### PR TITLE
change favicon domain url to dewey-server.azurewebsites.net

### PR DESCRIPTION
**Pull request by artemgrygor**
Hey guy,
haven't succeeded with favicon problem. So I've implemented a small nodejs  application "dewey-server" which hosted on my Azure portal by url http://dewey-server.azurewebsites.net/favicon?query=www.fb.com
and pointed deweyapp to send url and get favicon back from there.

@outcoldman @jamiewilson could you please check it when you have a time. I've called it dewey-server (maybe in a future we will need some more api). Also maybe I need to link this repository to dewey organization.

P.S. as always any comments are welcome.

### CODE REVIEW

**Comment by artemgrygor** [comment]
If everything is OK I will add Readme file and some tests

**Comment by jamiewilson** [comment]
Works well for me! Nice work Artem. Thanks! @outcoldman, what do you think?

**Comment by outcoldman** [comment]
@artemgrygor nice work! if it works, let's merge it in.
Could you move this project in deweyapp org https://github.com/deweyapp ? 
If you don't have rights to do that - we can fix that.

**Comment by artemgrygor** [comment]
@outcoldman Looks like I don't have rights.

**Comment by outcoldman** [comment]
@artemgrygor it seems like it does not have an ability for me to give you ownership role for this project, but I created a new repository with write access for you https://github.com/deweyapp/dewey-server 

Could you just move your code to it?

**Comment by artemgrygor** [comment]
@outcoldman done. There is one problem. Looks like I can't link an azure with a new github repository to publish automatically (http://feedback.azure.com/forums/169385-websites/suggestions/6532040-allow-deployment-from-github-organization-reposito). We could fix it later or setup it to the fork.

**Pull request merged**
