### PR TITLE
Fix the loading icon when showThumbnail=false

### PR DESCRIPTION
**Pull request by rlasjunies**
Here is a proposal on this annoying spinning icon.

But the way do you have idea to solve the image creation?

### CODE REVIEW

**Comment by outcoldman** [comment]
@rlasjunies thanks, looks good to me. @artemgrygor are you ok to merge it?

**Comment by artemgrygor** [comment]
@outcoldman I'm ok too! @rlasjunies thank you for your help! Regarding the image creation, there are few options. We are using right now 3d party API and can't use it anymore for different reasons. Of course, we can do it on our server but it would be resource intensive for us. Either generate a screenshot on a client side. or something like this  https://github.com/brenden/node-webshot 
We will appreciate any help here or ideas.

**Comment by artemgrygor** [comment]
@outcoldman should I merge it and we will publish it?

**Comment by outcoldman** [comment]
@rlasjunies :+1: thank you

I will publish an updated version on this week

**Comment by outcoldman** [comment]
@rlasjunies @artemgrygor published!

**Pull request merged**
